name: Publish assets to GitHub release

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *" # Every day at 2:00am
  push:
    tags:
      - 'v*.*.*'

jobs:
  check-version:
    name: Check the version validity
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # No need to check the version for dry run (cron or workflow_dispatch)
    steps:
      - uses: actions/checkout@v5
      # Check if the tag has the v<nmumber>.<number>.<number> format.
      # If yes, it means we are publishing an official release.
      # If no, we are releasing a RC, so no need to check the version.
      - name: Check tag format
        if: startsWith(github.ref, 'refs/tags/')
        id: check-tag-format
        run: |
          escaped_tag=$(printf "%q" ${{ github.ref_name }})

          if [[ $escaped_tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "stable=true" >> $GITHUB_OUTPUT
          else
            echo "stable=false" >> $GITHUB_OUTPUT
          fi
      - name: Check release validity
        if: startsWith(github.ref, 'refs/tags/') && steps.check-tag-format.outputs.stable == 'true'
        run: bash .github/scripts/check-release.sh
      
      # Create GitHub Release
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-linux:
    name: Publish binary for Linux
    runs-on: ubuntu-latest
    needs: check-version
    permissions:
      contents: write
    container:
      # Use ubuntu-22.04 to compile with glibc 2.35
      image: ubuntu:22.04
    steps:
      - uses: actions/checkout@v5
      - name: Install needed dependencies
        run: |
          apt-get update && apt-get install -y curl
          apt-get install build-essential -y
      - uses: dtolnay/rust-toolchain@1.89
      - name: Build
        run: cargo build --release --locked
      # No need to upload binaries for dry run (cron or workflow_dispatch)
      - name: Upload binaries to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/meilisearch
          name: meilisearch-linux-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-macos-windows:
    name: Publish binary for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: check-version
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, windows-2022]
        include:
          - os: macos-13
            artifact_name: meilisearch
            asset_name: meilisearch-macos-amd64
          - os: windows-2022
            artifact_name: meilisearch.exe
            asset_name: meilisearch-windows-amd64.exe
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@1.89
      - name: Build
        run: cargo build --release --locked
      # No need to upload binaries for dry run (cron or workflow_dispatch)
      - name: Upload binaries to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/${{ matrix.artifact_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-macos-apple-silicon:
    name: Publish binary for macOS silicon
    runs-on: macos-13
    needs: check-version
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            asset_name: meilisearch-macos-apple-silicon
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Installing Rust toolchain
        uses: dtolnay/rust-toolchain@1.89
        with:
          profile: minimal
          target: ${{ matrix.target }}
      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}
      - name: Upload the binary to release
        # No need to upload binaries for dry run (cron or workflow_dispatch)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: target/${{ matrix.target }}/release/meilisearch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-aarch64:
    name: Publish binary for aarch64
    runs-on: ubuntu-latest
    needs: check-version
    permissions:
      contents: write
    env:
      DEBIAN_FRONTEND: noninteractive
    container:
      # Use ubuntu-22.04 to compile with glibc 2.35
      image: ubuntu:22.04
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            asset_name: meilisearch-linux-aarch64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install needed dependencies
        run: |
          apt-get update -y && apt upgrade -y
          apt-get install -y curl build-essential gcc-aarch64-linux-gnu
      - name: Set up Docker for cross compilation
        run: |
          apt-get install -y curl apt-transport-https ca-certificates software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
          add-apt-repository "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          apt-get update -y && apt-get install -y docker-ce
      - name: Installing Rust toolchain
        uses: dtolnay/rust-toolchain@1.89
        with:
          profile: minimal
          target: ${{ matrix.target }}
      - name: Configure target aarch64 GNU
        ## Environment variable is not passed using env:
        ## LD gold won't work with MUSL
        # env:
        #   JEMALLOC_SYS_WITH_LG_PAGE: 16
        #   RUSTFLAGS: '-Clink-arg=-fuse-ld=gold'
        run: |
          echo '[target.aarch64-unknown-linux-gnu]' >> ~/.cargo/config
          echo 'linker = "aarch64-linux-gnu-gcc"' >> ~/.cargo/config
          echo 'JEMALLOC_SYS_WITH_LG_PAGE=16' >> $GITHUB_ENV
      - name: Install a default toolchain that will be used to build cargo cross
        run: |
          rustup default stable
      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          use-cross: true
          args: --release --target ${{ matrix.target }}
        env:
          CROSS_DOCKER_IN_DOCKER: true
      - name: List target output files
        run: ls -lR ./target
      - name: Upload the binary to release
        # No need to upload binaries for dry run (cron or workflow_dispatch)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: target/${{ matrix.target }}/release/meilisearch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-openapi-file:
    name: Publish OpenAPI file
    needs: check-version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Generate OpenAPI file
        run: |
          cd crates/openapi-generator
          cargo run --release -- --pretty --output ../../meilisearch.json
      - name: Upload OpenAPI to Release
        # No need to upload for dry run (cron or workflow_dispatch)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: ./meilisearch.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
